[project]
authors = ["Hernan Grecco <hgrecco@gmail.com>"]
channels = ["https://prefix.dev/conda-forge", "conda-forge"]
name = "Datos VAMP721"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
from-app = "python plantsinplates-app"
from-dev = "python __main__.py"

build = "python -m zipfile -c plantsinplates-app __main__.py pixi.toml pixi.lock plantsinplates"
publish = { cmd = "scp plantsinplates-app df:/home/hgrecco/html/pkg", depends-on = [
  "build",
] }

download = """python -c "import requests; open('plantsinplates-app','wb').write(requests.get('http://users.df.uba.ar/hgrecco/pkg/plantsinplates-app').content)" """
update-app = { cmd = """python -c "import zipfile; z=zipfile.ZipFile('plantsinplates-app');z.extract('pixi.toml');z.extract('pixi.lock')" """, depends-on = [
  "download",
] }


[dependencies]
python = "==3.12"
ipykernel = "*"
jupyter = ">=1.1.1,<2"
scikit-image = ">=0.25.1,<0.26"
numpy = ">=2.2.3,<3"
scipy = ">=1.15.2,<2"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2.3,<3"
openpyxl = ">=3.1.5,<4"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
bioio = ">=0.0.1, <0.0.2"
bioio-czi = ">=1.0.2, <2"
bioio-ome-tiff = ">=1.0.1, <2"
pandas-stubs = "*"
matplotlib-stubs = "*"
scipy-stubs = "*"

[environments]
lint = { features = ["lint"], no-default-feature = true }

[feature.lint.dependencies]
python = "==3.12"
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]
